"""Evidently data-drift report: reference window vs current window.

Drift is evaluated on the model's input features (built with the same
point-in-time pipeline used for training), not on raw columns, so the report
answers the question that actually matters in production: has the distribution
the model scores on moved?

Writes an HTML report plus a compact markdown summary with the per-feature drift
table. Evidently is imported here only - the test suite and CI never touch it.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import pandas as pd
from evidently import Report
from evidently.presets import DataDriftPreset

from fraud_ml.features.build import FEATURE_COLUMNS, build_features


def feature_frame(df: pd.DataFrame) -> pd.DataFrame:
    return build_features(df)[FEATURE_COLUMNS]


def run_report(reference: pd.DataFrame, current: pd.DataFrame) -> Any:
    report = Report([DataDriftPreset()])
    return report.run(current_data=feature_frame(current), reference_data=feature_frame(reference))


def summarize(snapshot: Any) -> dict[str, Any]:
    """Extract the drifted-columns headline and per-feature drift rows."""
    headline: dict[str, Any] = {}
    rows: list[dict[str, Any]] = []
    for metric in snapshot.dict().get("metrics", []):
        config = metric.get("config", {})
        metric_type = str(config.get("type", ""))
        if metric_type.endswith("DriftedColumnsCount"):
            headline = dict(metric.get("value", {}))
        elif metric_type.endswith("ValueDrift"):
            threshold = float(config.get("threshold", 0.1))
            score = float(metric["value"])
            rows.append(
                {
                    "feature": config.get("column", "?"),
                    "method": config.get("method", "?"),
                    "score": score,
                    "threshold": threshold,
                    "drifted": score >= threshold,
                }
            )
    return {"headline": headline, "rows": rows}


def write_summary_md(summary: dict[str, Any], path: Path) -> None:
    headline = summary["headline"]
    lines = [
        "# Data drift summary",
        "",
        "Generated by `python -m fraud_ml.drift.report` (Evidently `DataDriftPreset`,",
        "reference vs current feature distributions).",
        "",
        f"Drifted features: **{headline.get('count', 0):.0f}** "
        f"({headline.get('share', 0.0):.0%} of monitored columns)",
        "",
        "| feature | method | drift score | threshold | drifted |",
        "| --- | --- | ---: | ---: | :---: |",
    ]
    for row in summary["rows"]:
        flag = "yes" if row["drifted"] else "no"
        lines.append(
            f"| `{row['feature']}` | {row['method']} | {row['score']:.4f} "
            f"| {row['threshold']:.2f} | {flag} |"
        )
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate an Evidently data-drift report.")
    parser.add_argument("--reference", type=Path, default=Path("data/reference.parquet"))
    parser.add_argument("--current", type=Path, default=Path("data/current.parquet"))
    parser.add_argument("--out", type=Path, default=Path("reports/drift_report.html"))
    args = parser.parse_args()

    reference = pd.read_parquet(args.reference)
    current = pd.read_parquet(args.current)
    print(f"reference rows={len(reference)}  current rows={len(current)}")

    snapshot = run_report(reference, current)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    snapshot.save_html(str(args.out))

    summary = summarize(snapshot)
    summary_path = args.out.with_name("drift_summary.md")
    write_summary_md(summary, summary_path)

    print(f"wrote {args.out} ({args.out.stat().st_size / 1e6:.2f} MB) and {summary_path}")
    headline = summary["headline"]
    print(f"drifted columns: {headline.get('count', 0):.0f} ({headline.get('share', 0.0):.0%})")
    for row in summary["rows"]:
        flag = "DRIFT" if row["drifted"] else "ok"
        print(f"  {row['feature']:<24}{row['score']:>10.4f}  {flag}")


if __name__ == "__main__":
    main()
